
classdef Landmark < ros.Message
    %Landmark MATLAB implementation of custom_msgs/Landmark
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'custom_msgs/Landmark' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ef8650c765d79ae0104db7234e507cf3' % The MD5 Checksum of the message definition
        PropertyList = { 'Distance' 'Angle' 'Id' } % List of non-constant message properties
        ROSPropertyList = { 'distance' 'angle' 'id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Distance
        Angle
        Id
    end
    methods
        function set.Distance(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Landmark', 'Distance');
            obj.Distance = single(val);
        end
        function set.Angle(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Landmark', 'Angle');
            obj.Angle = single(val);
        end
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Landmark', 'Id');
            obj.Id = uint32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.custom_msgs.Landmark.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.custom_msgs.Landmark(strObj);
        end
    end
end
