
classdef Landmarks < ros.Message
    %Landmarks MATLAB implementation of custom_msgs/Landmarks
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'custom_msgs/Landmarks' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b7bf04cf814abf6f0d63f32ee5801c33' % The MD5 Checksum of the message definition
        PropertyList = { 'Landmarks_' } % List of non-constant message properties
        ROSPropertyList = { 'landmarks' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.custom_msgs.Landmark' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Landmarks_
    end
    methods
        function set.Landmarks_(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.custom_msgs.Landmark.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.custom_msgs.Landmark'};
            validateattributes(val, validClasses, validAttributes, 'Landmarks', 'Landmarks_')
            obj.Landmarks_ = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.custom_msgs.Landmarks.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.custom_msgs.Landmarks(strObj);
        end
    end
end
