// Generated by gencpp from file custom_msgs/Landmark.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LANDMARK_H
#define CUSTOM_MSGS_MESSAGE_LANDMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct Landmark_
{
  typedef Landmark_<ContainerAllocator> Type;

  Landmark_()
    : distance(0.0)
    , angle(0.0)
    , id(0)  {
    }
  Landmark_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::custom_msgs::Landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Landmark_<ContainerAllocator> const> ConstPtr;

}; // struct Landmark_

typedef ::custom_msgs::Landmark_<std::allocator<void> > Landmark;

typedef boost::shared_ptr< ::custom_msgs::Landmark > LandmarkPtr;
typedef boost::shared_ptr< ::custom_msgs::Landmark const> LandmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Landmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Landmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/marco/PROYECTOS/MRS_EKF_MatLab/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Landmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Landmark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8650c765d79ae0104db7234e507cf3";
  }

  static const char* value(const ::custom_msgs::Landmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8650c765d79ae0ULL;
  static const uint64_t static_value2 = 0x104db7234e507cf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Landmark";
  }

  static const char* value(const ::custom_msgs::Landmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
"float32 angle\n"
"uint32 id\n"
;
  }

  static const char* value(const ::custom_msgs::Landmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Landmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Landmark_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LANDMARK_H
