// Generated by gencpp from file custom_msgs/Landmarks.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LANDMARKS_H
#define CUSTOM_MSGS_MESSAGE_LANDMARKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/Landmark.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct Landmarks_
{
  typedef Landmarks_<ContainerAllocator> Type;

  Landmarks_()
    : landmarks()  {
    }
  Landmarks_(const ContainerAllocator& _alloc)
    : landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::custom_msgs::Landmark_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::custom_msgs::Landmark_<ContainerAllocator> >::other >  _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::custom_msgs::Landmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Landmarks_<ContainerAllocator> const> ConstPtr;

}; // struct Landmarks_

typedef ::custom_msgs::Landmarks_<std::allocator<void> > Landmarks;

typedef boost::shared_ptr< ::custom_msgs::Landmarks > LandmarksPtr;
typedef boost::shared_ptr< ::custom_msgs::Landmarks const> LandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Landmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Landmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/marco/PROYECTOS/MRS_EKF_MatLab/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Landmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Landmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7bf04cf814abf6f0d63f32ee5801c33";
  }

  static const char* value(const ::custom_msgs::Landmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7bf04cf814abf6fULL;
  static const uint64_t static_value2 = 0x0d63f32ee5801c33ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Landmarks";
  }

  static const char* value(const ::custom_msgs::Landmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Landmark[] landmarks\n"
"================================================================================\n"
"MSG: custom_msgs/Landmark\n"
"float32 distance\n"
"float32 angle\n"
"uint32 id\n"
;
  }

  static const char* value(const ::custom_msgs::Landmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Landmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Landmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Landmarks_<ContainerAllocator>& v)
  {
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msgs::Landmark_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LANDMARKS_H
